# Generated by Django 3.1.3 on 2020-12-04 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201204_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_date',
            new_name='post_datetime',
        ),
    ]
