# Generated by Django 3.1.3 on 2020-11-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='guest-user.jpg', upload_to='profile_pictures'),
        ),
    ]
