# Generated by Django 3.1.3 on 2020-12-02 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201130_2131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
